version: "3"
services:
  diarymd:
    image: aceberg/diarymd
    restart: unless-stopped
    user: "1000:1000" # put your user UID:GID here
    volumes:
    - ~/.dockerdata/DiaryMD:/data/DiaryMD  # config
    - ~/.dockerdata/DiaryRepo:/repo        # diary
    environment:
      TZ: Asia/Novosibirsk   # required, default: ""
      REPOPATH: /repo        # optinal, path to diary dir, default: ""
# WARNING!
# Mounted volumes must have write permission for non-root user
  
  forauth:
    image: aceberg/forauth      
    restart: unless-stopped
    ports:
    - 8800:8800 # Proxy port
    - 8801:8801 # Config port
    volumes:
    - ~/.dockerdata/forauth:/data/ForAuth
    environment:
      TZ: Asia/Novosibirsk          # required: needs your TZ for correct time
      FA_TARGET: "diarymd:8854"     # optional: path to diarymd host:port  
      FA_AUTH: "true"               # optional: true - enabled, default: false
      FA_AUTH_EXPIRE: 7d            # optional: expiration time, default: 7d
      FA_AUTH_PASSWORD: "$$2a$$10$$wGLUHXh2cRN1257uGg1s5eZvYgnjw8wB9vAcfcHqqqrxm5hvBqAzK" 
      # WARNING! If password is set as environment variable, every '$' character must be escaped with another '$', like this '$$'
      # optional: password encrypted with bcrypt, how-to: https://github.com/aceberg/ForAuth/blob/main/docs/BCRYPT.md (In this example FA_AUTH_PASSWORD=pw)
      FA_AUTH_USER: user            # optional: username